# Generated by Django 4.2.1 on 2023-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_category_phones_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phones',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterField(
            model_name='phones',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
