# Generated by Django 4.2.1 on 2023-07-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0007_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
