# Generated by Django 4.2.1 on 2023-07-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
